//! Auto-generated SAI bindings
//!
//! This module contains FFI bindings to the SAI (Switch Abstraction Interface)
//! C API, automatically generated by bindgen from the official SAI headers.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(improper_ctypes)]

include!(concat!(env!("OUT_DIR"), "/sai_bindings.rs"));
