//! SAI Constants that aren't generated by bindgen
//!
//! These constants are defined as macros in SAI headers and won't be
//! automatically generated by bindgen. We define them here manually.

use crate::bindings::*;

// SAI Status codes (from saistatus.h)
// These are macro-defined as SAI_STATUS_CODE(N) which expands to -(N) on Unix
// Bindgen cannot translate C macros, so we define them manually
pub const SAI_STATUS_FAILURE: sai_status_t = -1;
pub const SAI_STATUS_NOT_SUPPORTED: sai_status_t = -2;
pub const SAI_STATUS_NO_MEMORY: sai_status_t = -3;
pub const SAI_STATUS_INSUFFICIENT_RESOURCES: sai_status_t = -4;
pub const SAI_STATUS_INVALID_PARAMETER: sai_status_t = -5;
pub const SAI_STATUS_ITEM_ALREADY_EXISTS: sai_status_t = -6;
pub const SAI_STATUS_ITEM_NOT_FOUND: sai_status_t = -7;
pub const SAI_STATUS_BUFFER_OVERFLOW: sai_status_t = -8;
pub const SAI_STATUS_INVALID_PORT_NUMBER: sai_status_t = -9;
pub const SAI_STATUS_INVALID_PORT_MEMBER: sai_status_t = -10;
pub const SAI_STATUS_INVALID_VLAN_ID: sai_status_t = -11;
pub const SAI_STATUS_UNINITIALIZED: sai_status_t = -12;
pub const SAI_STATUS_TABLE_FULL: sai_status_t = -13;
pub const SAI_STATUS_MANDATORY_ATTRIBUTE_MISSING: sai_status_t = -14;
pub const SAI_STATUS_NOT_IMPLEMENTED: sai_status_t = -15;
pub const SAI_STATUS_ADDR_NOT_FOUND: sai_status_t = -16;
pub const SAI_STATUS_OBJECT_IN_USE: sai_status_t = -17;
pub const SAI_STATUS_INVALID_OBJECT_TYPE: sai_status_t = -18;
pub const SAI_STATUS_INVALID_OBJECT_ID: sai_status_t = -19;
pub const SAI_STATUS_INVALID_NV_STORAGE: sai_status_t = -20;
pub const SAI_STATUS_NV_STORAGE_FULL: sai_status_t = -21;
pub const SAI_STATUS_INVALID_ATTRIBUTE_0: sai_status_t = -0x10000;

// SAI API type and enum values (from sai.h)
// The sai_api_t enum is defined in sai.h which includes experimental dependencies.
// We manually define the type alias and enum values we need for L2 switching.
// Type names must match SAI C API names for FFI compatibility.
#[allow(non_camel_case_types)]
pub type sai_api_t = u32;

pub const SAI_API_UNSPECIFIED: sai_api_t = 0;
pub const SAI_API_SWITCH: sai_api_t = 1;
pub const SAI_API_PORT: sai_api_t = 2;
pub const SAI_API_FDB: sai_api_t = 3;
pub const SAI_API_VLAN: sai_api_t = 4;
pub const SAI_API_LAG: sai_api_t = 16;
pub const SAI_API_BRIDGE: sai_api_t = 33;

// Service method table function pointer types (from sai.h)
// Type names must match SAI C API names for FFI compatibility.
use std::os::raw::{c_char, c_int};

#[allow(non_camel_case_types)]
pub type sai_profile_get_value_fn =
    Option<unsafe extern "C" fn(profile_id: u32, variable: *const c_char) -> *const c_char>;

#[allow(non_camel_case_types)]
pub type sai_profile_get_next_value_fn = Option<
    unsafe extern "C" fn(
        profile_id: u32,
        variable: *mut *const c_char,
        value: *mut *const c_char,
    ) -> c_int,
>;

// Service method table (from sai.h)
// This struct is passed to sai_api_initialize()
#[repr(C)]
#[derive(Debug, Copy, Clone)]
#[allow(non_camel_case_types)]
pub struct sai_service_method_table_t {
    pub profile_get_value: sai_profile_get_value_fn,
    pub profile_get_next_value: sai_profile_get_next_value_fn,
}
